#!/usr/bin/env python3
"""
Build tool for Companion - Inlines assets into companion.py

Reads the three asset files (index.html, pdf.min.mjs, pdf.worker.min.mjs),
fills the empty string constants in the source, and removes the _load_assets()
function and its call, producing a self-contained single-file distribution.
"""

import re
import urllib.request
from pathlib import Path


def fetch_url(url: str, cache_path: str) -> str:
    """Fetch content from URL or load from cache"""
    cache_file = Path(cache_path)

    # Check if cached version exists
    if cache_file.exists():
        print(f"📦 Loading from cache: {cache_path}")
        with open(cache_file, "r", encoding="utf-8") as f:
            content = f.read()
        print(f"✅ Loaded {len(content):,} bytes from cache")
        return content

    # Fetch from CDN
    print(f"📥 Fetching {url}...")
    with urllib.request.urlopen(url) as response:
        content = response.read().decode("utf-8")
    print(f"✅ Fetched {len(content):,} bytes")

    # Cache for future use
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    with open(cache_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"💾 Cached to {cache_path}")

    return content


def _replace_or_die(source: str, old: str, new: str, label: str) -> str:
    """Replace a string in source, or exit with an error if not found."""
    if old not in source:
        print(f"❌ ERROR: Could not find {label} in source.")
        print("   The source file may have been modified. Please update build.py.")
        exit(1)
    return source.replace(old, new, 1)


def build_companion():
    """Build companion.py with inlined assets"""
    print("🔨 Building Companion with inlined assets...\n")

    # Read source file
    print("📖 Reading src/companion.py...")
    with open("src/companion.py", "r", encoding="utf-8") as f:
        source = f.read()

    # Read asset files
    print("📄 Reading src/index.html...")
    with open("src/index.html", "r", encoding="utf-8") as f:
        html_content = f.read()

    pdf_js_url = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.149/pdf.min.mjs"
    pdf_worker_url = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.149/pdf.worker.min.mjs"
    pdf_js_content = fetch_url(pdf_js_url, "js_deps/pdf.min.mjs")
    pdf_worker_content = fetch_url(pdf_worker_url, "js_deps/pdf.worker.min.mjs")

    # Fill the three asset constants
    print("\n🔄 Filling asset constants...")
    source = _replace_or_die(source, '_INDEX_HTML = ""', f'_INDEX_HTML = """{html_content}"""', '_INDEX_HTML = ""')
    print(f"✅ Inlined index.html ({len(html_content):,} bytes)")

    import base64

    pdf_js_b64 = base64.b64encode(pdf_js_content.encode("utf-8")).decode("ascii")
    pdf_worker_b64 = base64.b64encode(pdf_worker_content.encode("utf-8")).decode("ascii")
    source = _replace_or_die(
        source,
        '_PDFJS_LIB = b""',
        f'_PDFJS_LIB = base64.b64decode("{pdf_js_b64}")',
        '_PDFJS_LIB = b""',
    )
    print(f"✅ Inlined pdf.min.mjs ({len(pdf_js_content):,} bytes)")
    source = _replace_or_die(
        source,
        '_PDFJS_WORKER = b""',
        f'_PDFJS_WORKER = base64.b64decode("{pdf_worker_b64}")',
        '_PDFJS_WORKER = b""',
    )
    print(f"✅ Inlined pdf.worker.min.mjs ({len(pdf_worker_content):,} bytes)")

    # Add base64 import (needed for the inlined PDF.js constants)
    source = _replace_or_die(source, "import contextlib\n", "import base64\nimport contextlib\n", "import contextlib")

    # Remove _load_assets() function definition
    print("\n🗑️  Removing _load_assets() function and call...")
    source = re.sub(
        r"\ndef _load_assets\(\):.*?(?=\n\n\n|\n@|\nclass )",
        "",
        source,
        count=1,
        flags=re.DOTALL,
    )

    # Remove the call to _load_assets() in _dispatch()
    source = _replace_or_die(
        source,
        "        if not _INDEX_HTML:\n            _load_assets()\n",
        "",
        "_load_assets() call in _dispatch()",
    )

    # Update docstring to mark as built version
    print("📝 Adding built version marker to docstring...")
    source = _replace_or_die(
        source,
        '#!/usr/bin/env python3\n"""',
        '#!/usr/bin/env python3\n"""\n'
        "⚠️  BUILT VERSION - This file was automatically generated by build.py\n"
        "    Source: src/companion.py\n"
        "    This version includes inlined assets for offline use.\n"
        "    For development, use src/companion.py which loads assets from files.\n"
        "\n"
        "LICENSE NOTICE:\n"
        "    - Companion code: MIT License, Copyright (c) 2025 c4ffein\n"
        "    - Embedded PDF.js library: Apache License 2.0, Copyright Mozilla Foundation\n"
        "    - See js_deps/LICENSE for full PDF.js license details\n"
        "    - Both licenses allow commercial and non-commercial use\n"
        "\n",
        "shebang/docstring marker",
    )

    # Write output file to root
    output_file = "companion.py"
    print(f"\n💾 Writing {output_file} to root...")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(source)

    output_size = len(source)
    original_size = len(open("src/companion.py", "r").read())

    print(f"✅ Build complete! Output: {output_file}")
    print(f"📦 Original size: {original_size:,} bytes")
    print(f"📦 Built size: {output_size:,} bytes")
    print(
        f"📦 Added: {output_size - original_size:,} bytes ({((output_size / original_size - 1) * 100):.1f}% increase)"
    )
    print("\n🎉 You can now distribute companion.py as a single file!")
    print("   The built version is at the root for easy access.")


if __name__ == "__main__":
    build_companion()
